---
name: "Build the documentation"
on:
  workflow_run:
    workflows:
      - Label PR
    types:
      - completed

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.result }}
    steps:
      - id: skip_check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(JSON.stringify(context, null, 2))
            let should_skip = false;
            let labels = context.payload.workflow_run.pull_requests[0].labels.map(label => { return label.name });

            if (!labels.includes("area:docs") {
              should_skip = true;
            }
            if (labels.includes("area:ci") {
              should_skip = false;
            }
            return should_skip;
  docs:
    runs-on: ubuntu-latest
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-sphinx python3-sphinx-rtd-theme python3-breathe doxygen

      - name: Build docs
        run: |
          make -C docs
