---
name: Label PR
on:
  # use pull_request_target here to label PRs. from the documentation:
  #
  # "This event runs in the context of the base of the pull request, rather
  # than in the context of the merge commit, as the pull_request event does"
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  #
  # this workflow is potentially dangerous because the workflow has access to
  # GitHub APIs, i.e. secrets.GITHUB_TOKEN, and the author of PRs, who might
  # not be a member of the repository, can modify the workflow.
  #
  # see also:
  # Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:

# this workflow needs write access to PRs because it add labels to PRs, or
# remove labels from PRs.
permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml

      - name: Save the PR number for other workflows triggered by this workflow
        # pass the PR number to other workflows.
        #
        # background: workflows triggered by workflow_run get an event context.
        # the context, somehow, does not include pull_requests object (I don't
        # know why GitHub does not include it). that means the triggered
        # workflow has no way to know the PR number. workaround the issue by
        # uploading the PR number as an artifact.
        run: |
          echo "${{ github.event.number }}" > pr_number.txt

      - name: Upload the PR number as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt
          if-no-files-found: error
