---
name: Metadata
on:
  workflow_run:
    workflows:
      - Label PR
    types:
      - completed

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.result }}
    steps:
      - name: Download the PR number from the triggering workflow as an artifact
        uses: actions/download-artifact@v3
        with:
          name: pr_number

      - name: Export the number
        run: |
          ls -al
          cat pr_number.txt
          PR_NUMBER=`cat pr_number.txt`
          echo "PR_NUMBER=${PR_NUMBER}" >> ${GITHUB_ENV}

      - id: skip_check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log("context");
            console.log(JSON.stringify(context, null, 2));
            let should_skip = false;
            let pr_number = parseInt(process.env.PR_NUMBER);

            pull_request = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
            });
            console.log("pull_request");
            console.log(JSON.stringify(pull_request, null, 2));

            let labels = pull_request.labels.map(label => { return label.name });

            if (!labels.includes("area:components")) {
              should_skip = true;
            }
            if (labels.includes("area:ci")) {
              should_skip = false;
            }
            return should_skip;
  test:
    runs-on: ubuntu-latest
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake -C devtools
    - run: |
        # Test if README.md is up-to-date with the metadata. If this test
        # fails, update README.md by:
        #
        # bundle exec rake -C devtools readme > README.md
        bundle exec rake -C devtools readme > README.md
        git diff --exit-code README.md
