---
name: Metadata
on:
  workflow_run:
    workflows:
      - Label PR
    types:
      - completed

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.result }}
    steps:
      - id: skip_check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(JSON.stringify(context, null, 2))
            let should_skip = false;
            let labels = context.payload.workflow_run.pull_requests[0].labels.map(label => { return label.name });

            if (!labels.includes("area:components") {
              should_skip = true;
            }
            if (labels.includes("area:ci") {
              should_skip = false;
            }
            return should_skip;
  test:
    runs-on: ubuntu-latest
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake -C devtools
    - run: |
        # Test if README.md is up-to-date with the metadata. If this test
        # fails, update README.md by:
        #
        # bundle exec rake -C devtools readme > README.md
        bundle exec rake -C devtools readme > README.md
        git diff --exit-code README.md
