---
name: PR Labeler
on:
  # run the workflow when a PR is created.
  # note that the workflow is triggered by pull_request_target, which means
  # the workflow runs with access to GITHUB_TOKEN.
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      # XXX required by TimonVS/pr-labeler-action
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
